matrix:
  GO_IMAGE:
    - 1.22
when:
  path:
    include: ["go/**", ".woodpecker/go.yml"]
  event: [push, cron]
  cron: go

steps:
  build:
    image: nixos/nix
    commands:
      - nix-channel --add https://nixos.org/channels/nixos-unstable nixos
      - nix-channel --update
      - nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - mkdir build/
      - nix-build go/${GO_IMAGE}/image.nix --no-out-link --option sandbox true -o build/go-${GO_IMAGE}.output 
      - ls -l -h -a build/
      - nix-shell -p skopeo --command "echo $CODEBERG_PKG_TOKEN | skopeo login -u Saturn745 --password-stdin codeberg.org && skopeo --insecure-policy copy docker-archive:./build/go-${GO_IMAGE}.output docker://codeberg.org/saturn745/pterodactyl-nixos:go${GO_IMAGE}"
    secrets: [ codeberg_pkg_token ]
