matrix:
  JAVA_IMAGE:
    - 17
when:
  path:
    include: ["java/**", ".woodpecker/java.yml"]
  event: [push, cron]
  cron: java

steps:
  build:
    image: nixos/nix
    commands:
      - nix-channel --add https://nixos.org/channels/nixos-unstable nixos
      - nix-channel --update
      - nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
      - mkdir build/
      - nix-build java/${JAVA_IMAGE}/image.nix --no-out-link --option sandbox true -o build/java-${JAVA_IMAGE}.output 
      - ls -l -h -a build/
      - nix-shell -p skopeo --command "echo $CODEBERG_PKG_TOKEN | skopeo login -u Saturn745 --password-stdin codeberg.org && skopeo --insecure-policy copy docker-archive:./build/java-${JAVA_IMAGE}.output docker://codeberg.org/saturn745/pterodactyl-nixos:java${JAVA_IMAGE}"
    secrets: [ codeberg_pkg_token ]
